# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('member', models.BooleanField()),
                ('caregiver', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('order_total', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('qty_dispensed', models.CharField(max_length=100)),
                ('qty_sold', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('discount', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('cashier', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CustomerOrder')),
            ],
        ),
    ]
